### REGISTER

POST http://localhost:3000/v1/register
Content-Type: application/json

{
  "name": "Maria das Couves",
  "email": "m.couves@teste.com.br",
  "password": "senhalegal",
  "phone": "5511912345678",
  "votes": [],
  "questions": []
}


### LOGIN

POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "email": "m.couves@teste.com.br",
  "password": "senhalegal"
}



### CREATE QUESTION

POST http://localhost:3000/v1/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoibS5jb3V2ZXNAdGVzdGUuY29tLmJyIiwiaWQiOiI2NWQ1ZjBkNTk4ZTU3MTIyYjgwMWFhOTUifSwiaWF0IjoxNzA4NTE5Njg1fQ.GkD8TzZyihgLDGyR_fhW8cl9Ke15QNSCZwM06UTSaT8

{
  "name": "Pintar o cabelo após os 30",
  "description": "Uma pessoa com mais de 30 anos deve pintar o cabelo",
  "sessionTime": {
    "year": 0,
    "month": 0,
    "day": 0,
    "hour": 1,
    "minutes": 30,
    "seconds": 47
  },
  "votes": [],
  "createdBy": "65d5f12598e57122b801aa98",
  "sessionStartedDate": null
}



### START SESSION

PATCH http://localhost:3000/v1/question/start/65d53d2e8c748aa4394d397f
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoibS5jb3V2ZXNAdGVzdGUuY29tLmJyIiwiaWQiOiI2NWQ1ZjBkNTk4ZTU3MTIyYjgwMWFhOTUifSwiaWF0IjoxNzA4NTE5Njg1fQ.GkD8TzZyihgLDGyR_fhW8cl9Ke15QNSCZwM06UTSaT8



### FIND STARTED

GET http://localhost:3000/v1/question/started?page=1&itemsPerPage=10
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiai5jb3V2ZXNAdGVzdGUuY29tLmJyIiwiaWQiOiI2NWQ2NDhiNDcwMTYxOTMzMzc1YjJiMzYiLCJwYXNzd29yZCI6IiQyYiQxMCRhV2Q0bWsuYzlQWkQzTXZWTmpOZkRlLjR5eXVLcnouYzZPL3RzUmNYeHhMcExNU05wNWZFSyJ9LCJpYXQiOjE3MDg2MDY3NjJ9.f02szwHQ98bvMwGuS7jET5AFAYSzTAoHB3aXeH_FKXk



### FIND BY CREATOR

GET http://localhost:3000/v1/question/65d648b470161933375b2b36/creator?page=1&itemsPerPage=10
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoiai5jb3V2ZXNAdGVzdGUuY29tLmJyIiwiaWQiOiI2NWQ2NDhiNDcwMTYxOTMzMzc1YjJiMzYiLCJwYXNzd29yZCI6IiQyYiQxMCRhV2Q0bWsuYzlQWkQzTXZWTmpOZkRlLjR5eXVLcnouYzZPL3RzUmNYeHhMcExNU05wNWZFSyJ9LCJpYXQiOjE3MDg2MDQxMjV9.mw-q0H5hLSeGT6KrNO_PrIENBVb46J96I-G1EPPgqiY



### VOTE
POST http://localhost:3000/v1/vote/65d53d2e8c748aa4394d397f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoibS5jb3V2ZXNAdGVzdGUuY29tLmJyIiwiaWQiOiI2NWQ1ZjBkNTk4ZTU3MTIyYjgwMWFhOTUifSwiaWF0IjoxNzA4NTE5Njg1fQ.GkD8TzZyihgLDGyR_fhW8cl9Ke15QNSCZwM06UTSaT8

{
  "userId": "65d52f2fc00aec119e7de0ac",
  "answer": "Sim"
}